apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  DB_HOST: "petclinic-db"
  DB_PORT: "5432"
  DB_NAME: "petclinic"
  DB_USER: "petclinic"

---
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secrets
type: Opaque
stringData:
  DB_PASSWORD: "petclinic"
  POSTGRES_PASSWORD: "petclinic"