apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yml
  - database.yml
  - customers-service.yml
  - vets-service.yml
  - visits-service.yml
  - api-gateway.yml

commonLabels:
  app.kubernetes.io/part-of: spring-petclinic
  app.kubernetes.io/managed-by: kustomize

namespace: default